name: Deploy Client to Production

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add front end remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
      - name: Deploy front end to Heroku
        run: git push heroku-frontend `git subtree split --prefix server main`:refs/heads/main --force